### ISSUE TITLE
telegram settings

### ISSUE THREAD

**Issue by magneticlab-ch** [Waterboy1602/Addarr#103]
What do i need to set into those 2 lines TOCKEN and PASSWORD ?
where to find those parameters ?

`#Telegram Configuration
telegram:
  token: token:longtoken
  password: password`

**Comment by Waterboy1602** [comment]
The token to let Addarr connect with Telegram you get by interacting with the BotFather. You can do this in the Telegram app itself. This bot will give you a token that you need to fill in in `config.yaml`

The password is something you can choose yourself to secure your Addarr bot from unauthorized interaction. You'll have to send your chosen password the first time you use Addarr.

```
#Telegram Configuration
telegram:
  token: #token:longtoken
  password: # Choose yourself
```
