### ISSUE TITLE
docker startup failure

### ISSUE THREAD

**Issue by PN62323424** [Waterboy1602/Addarr#118]
stderr: Traceback (most recent call last):
stderr:   File "/app/src/addarr.py", line 12, in <module>
stderr:     from commons import checkAllowed, checkId, authentication, format_bytes, getAuthChats
stderr:   File "/app/src/commons.py", line 5, in <module>
stderr:     from config import config
stderr:   File "/app/src/config.py", line 5, in <module>
stderr:     config = yaml.safe_load(open(CONFIG_PATH, encoding="utf8"))
stderr:   File "/usr/local/lib/python3.10/site-packages/yaml/__init__.py", line 125, in safe_load
stderr:     return load(stream, SafeLoader)
stderr:   File "/usr/local/lib/python3.10/site-packages/yaml/__init__.py", line 81, in load
stderr:     return loader.get_single_data()
stderr:   File "/usr/local/lib/python3.10/site-packages/yaml/constructor.py", line 49, in get_single_data
stderr:     node = self.get_single_node()
stderr:   File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 36, in get_single_node
stderr:     document = self.compose_document()
stderr:   File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 55, in compose_document
stderr:     node = self.compose_node(None, None)
stderr:   File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 84, in compose_node
stderr:     node = self.compose_mapping_node(anchor)
stderr:   File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 133, in compose_mapping_node
stderr:     item_value = self.compose_node(node, item_key)
stderr:   File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 84, in compose_node
stderr:     node = self.compose_mapping_node(anchor)
stderr:   File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 127, in compose_mapping_node
stderr:     while not self.check_event(MappingEndEvent):
stderr:   File "/usr/local/lib/python3.10/site-packages/yaml/parser.py", line 98, in check_event
stderr:     self.current_event = self.state()
stderr:   File "/usr/local/lib/python3.10/site-packages/yaml/parser.py", line 428, in parse_block_mapping_key
stderr:     if self.check_token(KeyToken):
stderr:   File "/usr/local/lib/python3.10/site-packages/yaml/scanner.py", line 116, in check_token
stderr:     self.fetch_more_tokens()
stderr:   File "/usr/local/lib/python3.10/site-packages/yaml/scanner.py", line 223, in fetch_more_tokens
stderr:     return self.fetch_value()
stderr:   File "/usr/local/lib/python3.10/site-packages/yaml/scanner.py", line 577, in fetch_value
stderr:     raise ScannerError(None, None,
stderr: yaml.scanner.ScannerError: mapping values are not allowed here
stderr:   in "/app/config.yaml", line 5, column 10
stderr: Traceback (most recent call last):
stderr:   File "/app/src/addarr.py", line 12, in <module>
stderr:     from commons import checkAllowed, checkId, authentication, format_bytes, getAuthChats
stderr:   File "/app/src/commons.py", line 5, in <module>
stderr:     from config import config
stderr:   File "/app/src/config.py", line 5, in <module>
stderr:     config = yaml.safe_load(open(CONFIG_PATH, encoding="utf8"))
stderr:   File "/usr/local/lib/python3.10/site-packages/yaml/__init__.py", line 125, in safe_load
stderr:     return load(stream, SafeLoader)
stderr:   File "/usr/local/lib/python3.10/site-packages/yaml/__init__.py", line 81, in load
stderr:     return loader.get_single_data()
stderr:   File "/usr/local/lib/python3.10/site-packages/yaml/constructor.py", line 49, in get_single_data
stderr:     node = self.get_single_node()
stderr:   File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 36, in get_single_node
stderr:     document = self.compose_document()
stderr:   File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 55, in compose_document
stderr:     node = self.compose_node(None, None)
stderr:   File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 84, in compose_node
stderr:     node = self.compose_mapping_node(anchor)
stderr:   File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 133, in compose_mapping_node
stderr:     item_value = self.compose_node(node, item_key)
stderr:   File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 84, in compose_node
stderr:     node = self.compose_mapping_node(anchor)
stderr:   File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 127, in compose_mapping_node
stderr:     while not self.check_event(MappingEndEvent):
stderr:   File "/usr/local/lib/python3.10/site-packages/yaml/parser.py", line 98, in check_event
stderr:     self.current_event = self.state()
stderr:   File "/usr/local/lib/python3.10/site-packages/yaml/parser.py", line 428, in parse_block_mapping_key
stderr:     if self.check_token(KeyToken):
stderr:   File "/usr/local/lib/python3.10/site-packages/yaml/scanner.py", line 116, in check_token
stderr:     self.fetch_more_tokens()
stderr:   File "/usr/local/lib/python3.10/site-packages/yaml/scanner.py", line 223, in fetch_more_tokens
stderr:     return self.fetch_value()
stderr:   File "/usr/local/lib/python3.10/site-packages/yaml/scanner.py", line 577, in fetch_value
stderr:     raise ScannerError(None, None,
stderr: yaml.scanner.ScannerError: mapping values are not allowed here
stderr:   in "/app/config.yaml", line 5, column 10
stderr: Traceback (most recent call last):
stderr:   File "/app/src/addarr.py", line 12, in <module>
stderr:     from commons import checkAllowed, checkId, authentication, format_bytes, getAuthChats
stderr:   File "/app/src/commons.py", line 5, in <module>
stderr:     from config import config
stderr:   File "/app/src/config.py", line 5, in <module>
stderr:     config = yaml.safe_load(open(CONFIG_PATH, encoding="utf8"))
stderr:   File "/usr/local/lib/python3.10/site-packages/yaml/__init__.py", line 125, in safe_load
stderr:     return load(stream, SafeLoader)
stderr:   File "/usr/local/lib/python3.10/site-packages/yaml/__init__.py", line 81, in load
stderr:     return loader.get_single_data()
stderr:   File "/usr/local/lib/python3.10/site-packages/yaml/constructor.py", line 49, in get_single_data
stderr:     node = self.get_single_node()
stderr:   File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 36, in get_single_node
stderr:     document = self.compose_document()
stderr:   File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 55, in compose_document
stderr:     node = self.compose_node(None, None)
stderr:   File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 84, in compose_node
stderr:     node = self.compose_mapping_node(anchor)
stderr:   File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 133, in compose_mapping_node
stderr:     item_value = self.compose_node(node, item_key)
stderr:   File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 84, in compose_node
stderr:     node = self.compose_mapping_node(anchor)
stderr:   File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 127, in compose_mapping_node
stderr:     while not self.check_event(MappingEndEvent):
stderr:   File "/usr/local/lib/python3.10/site-packages/yaml/parser.py", line 98, in check_event
stderr:     self.current_event = self.state()
stderr:   File "/usr/local/lib/python3.10/site-packages/yaml/parser.py", line 428, in parse_block_mapping_key
stderr:     if self.check_token(KeyToken):
stderr:   File "/usr/local/lib/python3.10/site-packages/yaml/scanner.py", line 116, in check_token
stderr:     self.fetch_more_tokens()
stderr:   File "/usr/local/lib/python3.10/site-packages/yaml/scanner.py", line 223, in fetch_more_tokens
stderr:     return self.fetch_value()
stderr:   File "/usr/local/lib/python3.10/site-packages/yaml/scanner.py", line 577, in fetch_value
stderr:     raise ScannerError(None, None,
stderr: yaml.scanner.ScannerError: mapping values are not allowed here
stderr:   in "/app/config.yaml", line 5, column 10
stderr: Traceback (most recent call last):
stderr:   File "/app/src/addarr.py", line 12, in <module>
stderr:     from commons import checkAllowed, checkId, authentication, format_bytes, getAuthChats
stderr:   File "/app/src/commons.py", line 5, in <module>
stderr:     from config import config
stderr:   File "/app/src/config.py", line 5, in <module>
stderr:     config = yaml.safe_load(open(CONFIG_PATH, encoding="utf8"))
stderr:   File "/usr/local/lib/python3.10/site-packages/yaml/__init__.py", line 125, in safe_load
stderr:     return load(stream, SafeLoader)
stderr:   File "/usr/local/lib/python3.10/site-packages/yaml/__init__.py", line 81, in load
stderr:     return loader.get_single_data()
stderr:   File "/usr/local/lib/python3.10/site-packages/yaml/constructor.py", line 49, in get_single_data
stderr:     node = self.get_single_node()
stderr:   File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 36, in get_single_node
stderr:     document = self.compose_document()
stderr:   File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 55, in compose_document
stderr:     node = self.compose_node(None, None)
stderr:   File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 84, in compose_node
stderr:     node = self.compose_mapping_node(anchor)
stderr:   File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 133, in compose_mapping_node
stderr:     item_value = self.compose_node(node, item_key)
stderr:   File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 84, in compose_node
stderr:     node = self.compose_mapping_node(anchor)
stderr:   File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 127, in compose_mapping_node
stderr:     while not self.check_event(MappingEndEvent):
stderr:   File "/usr/local/lib/python3.10/site-packages/yaml/parser.py", line 98, in check_event
stderr:     self.current_event = self.state()
stderr:   File "/usr/local/lib/python3.10/site-packages/yaml/parser.py", line 428, in parse_block_mapping_key
stderr:     if self.check_token(KeyToken):
stderr:   File "/usr/local/lib/python3.10/site-packages/yaml/scanner.py", line 116, in check_token
stderr:     self.fetch_more_tokens()
stderr:   File "/usr/local/lib/python3.10/site-packages/yaml/scanner.py", line 223, in fetch_more_tokens
stderr:     return self.fetch_value()
stderr:   File "/usr/local/lib/python3.10/site-packages/yaml/scanner.py", line 577, in fetch_value
stderr:     raise ScannerError(None, None,
stderr: yaml.scanner.ScannerError: mapping values are not allowed here
stderr:   in "/app/config.yaml", line 5, column 10
stderr: Traceback (most recent call last):
stderr:   File "/app/src/addarr.py", line 12, in <module>
stderr:     from commons import checkAllowed, checkId, authentication, format_bytes, getAuthChats
stderr:   File "/app/src/commons.py", line 5, in <module>
stderr:     from config import config
stderr:   File "/app/src/config.py", line 5, in <module>
stderr:     config = yaml.safe_load(open(CONFIG_PATH, encoding="utf8"))
stderr:   File "/usr/local/lib/python3.10/site-packages/yaml/__init__.py", line 125, in safe_load
stderr:     return load(stream, SafeLoader)
stderr:   File "/usr/local/lib/python3.10/site-packages/yaml/__init__.py", line 81, in load
stderr:     return loader.get_single_data()
stderr:   File "/usr/local/lib/python3.10/site-packages/yaml/constructor.py", line 49, in get_single_data
stderr:     node = self.get_single_node()
stderr:   File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 36, in get_single_node
stderr:     document = self.compose_document()
stderr:   File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 55, in compose_document
stderr:     node = self.compose_node(None, None)
stderr:   File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 84, in compose_node
stderr:     node = self.compose_mapping_node(anchor)
stderr:   File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 133, in compose_mapping_node
stderr:     item_value = self.compose_node(node, item_key)
stderr:   File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 84, in compose_node
stderr:     node = self.compose_mapping_node(anchor)
stderr:   File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 127, in compose_mapping_node
stderr:     while not self.check_event(MappingEndEvent):
stderr:   File "/usr/local/lib/python3.10/site-packages/yaml/parser.py", line 98, in check_event
stderr:     self.current_event = self.state()
stderr:   File "/usr/local/lib/python3.10/site-packages/yaml/parser.py", line 428, in parse_block_mapping_key
stderr:     if self.check_token(KeyToken):
stderr:   File "/usr/local/lib/python3.10/site-packages/yaml/scanner.py", line 116, in check_token
stderr:     self.fetch_more_tokens()
stderr:   File "/usr/local/lib/python3.10/site-packages/yaml/scanner.py", line 223, in fetch_more_tokens
stderr:     return self.fetch_value()
stderr:   File "/usr/local/lib/python3.10/site-packages/yaml/scanner.py", line 577, in fetch_value
stderr:     raise ScannerError(None, None,
stderr: yaml.scanner.ScannerError: mapping values are not allowed here
stderr:   in "/app/config.yaml", line 5, column 10
stderr: Traceback (most recent call last):
stderr:   File "/app/src/addarr.py", line 12, in <module>
stderr:     from commons import checkAllowed, checkId, authentication, format_bytes, getAuthChats
stderr:   File "/app/src/commons.py", line 5, in <module>
stderr:     from config import config
stderr:   File "/app/src/config.py", line 5, in <module>
stderr:     config = yaml.safe_load(open(CONFIG_PATH, encoding="utf8"))
stderr:   File "/usr/local/lib/python3.10/site-packages/yaml/__init__.py", line 125, in safe_load
stderr:     return load(stream, SafeLoader)
stderr:   File "/usr/local/lib/python3.10/site-packages/yaml/__init__.py", line 81, in load
stderr:     return loader.get_single_data()
stderr:   File "/usr/local/lib/python3.10/site-packages/yaml/constructor.py", line 49, in get_single_data
stderr:     node = self.get_single_node()
stderr:   File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 36, in get_single_node
stderr:     document = self.compose_document()
stderr:   File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 55, in compose_document
stderr:     node = self.compose_node(None, None)
stderr:   File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 84, in compose_node
stderr:     node = self.compose_mapping_node(anchor)
stderr:   File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 133, in compose_mapping_node
stderr:     item_value = self.compose_node(node, item_key)
stderr:   File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 84, in compose_node
stderr:     node = self.compose_mapping_node(anchor)
stderr:   File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 127, in compose_mapping_node
stderr:     while not self.check_event(MappingEndEvent):
stderr:   File "/usr/local/lib/python3.10/site-packages/yaml/parser.py", line 98, in check_event
stderr:     self.current_event = self.state()
stderr:   File "/usr/local/lib/python3.10/site-packages/yaml/parser.py", line 428, in parse_block_mapping_key
stderr:     if self.check_token(KeyToken):
stderr:   File "/usr/local/lib/python3.10/site-packages/yaml/scanner.py", line 116, in check_token
stderr:     self.fetch_more_tokens()
stderr:   File "/usr/local/lib/python3.10/site-packages/yaml/scanner.py", line 223, in fetch_more_tokens
stderr:     return self.fetch_value()
stderr:   File "/usr/local/lib/python3.10/site-packages/yaml/scanner.py", line 577, in fetch_value
stderr:     raise ScannerError(None, None,
stderr: yaml.scanner.ScannerError: mapping values are not allowed here
stderr:   in "/app/config.yaml", line 5, column 10

this is my config.yaml
#Sonarr Configuration
sonarr:
  server:
    addr:10.0.0.75
    port : 8989 # Default is 8989
    path:/tv/sonarr/ # Default is / . If set, it must start and finish with / . Eg: /sonarr/
    ssl: false #default false
  auth:
    apikey:xxxxxxxxxxx
    username: #
    password: #
  search: true
  seasonFolder: true
  languageProfile: English
  excludedRootFolders: # If set must not have a trailing slash Eg: /mnt/Media
    - # First excluded folder, add others with a "-" on a new line (same indentation)
  excludedQualityProfiles:
    - 
  defaultTags: # If set must be existing tags
    - telegram
  adminRestrictions: false

#Radarr Configuration
radarr:
  server:
    addr:10.0.0.75
    port : 7878 # Default is 7878
    path:/movies/radarr/ # Default is / . If set, it must start and finish with / . Eg: /radarr/
    ssl: false #default false
  auth:
    apikey:xxxxxxxxxxx
    username: #
    password: #
  search: true
  minimumAvailability: announced
  excludedRootFolders: # If set must not have a trailing slash Eg: /mnt/Media
    - # First excluded folder, add others with a "-" on a new line (same indentation)
  excludedQualityProfiles:
    - #
  defaultTags: # If set must be existing tags
    - telegram
  adminRestrictions: false
  
#Telegram Configuration
telegram:
  token:xxxxxxxxxxx
  password:xxxxxxxxxxx

#Transmission Configuration
transmission:
  enable: true #enable the transmission commands
  onlyAdmin: true #transmission command  will only work for admins
  host:10.0.0.75 # IP-adres of the Transmission service
  authentication: true #is transmission protected with a password?
  username:xxxxxxxxxxx
  password:xxxxxxxxxxx

sabnzbd:
  enable: true
  onlyAdmin: true
  server:
    addr: #
    port: 8090 # Default is 8090
    path: / # Default is / . If set, it must start and finish with / . Eg: /sonarr/
    ssl: false #default false
  auth:
    apikey: #
    username: #
    password: #

# Optional settings:
##Language
language: en-us # en-us, es-es, it-it, nl-be, pt-pt

##Entrypoints
entrypointAuth: auth #auth or a custom entrypoint
entrypointHelp: help #help entrypoint
entrypointAdd: start #start or a custom entrypoint
entrypointAllSeries: allSeries #allSeries or a custom entrypoint
entrypointAllMovies: allMovies #allMovies or a custom entrypoint
entrypointTransmission: transmission #transmission or a custom entrypoint
entrypointSabnzbd: sabnzbd #sabnzbd or a custom entrypoint

##Restrict some commands to only admins and/or provide extra authorization by usernames
enableAdmin: true #Check admin.txt
enableAllowlist: false #Check allowlist.txt - very restrictive!

##Logging
logToConsole: true
debugLogging: true

**Comment by Waterboy1602** [comment]
There are some problems with your `config.yaml`. It should look like this:

```
#Sonarr Configuration
sonarr:
  server:
    addr: 10.0.0.75
    port: 8989 # Default is 8989
    path: /tv/sonarr/ # Default is / . If set, it must start and finish with / . Eg: /sonarr/
    ssl: false #default false
  auth:
    apikey: xxxxxxxxxxx
    username: #
    password: #
  search: true
  seasonFolder: true
  languageProfile: English
  excludedRootFolders: # If set must not have a trailing slash Eg: /mnt/Media
    - # First excluded folder, add others with a "-" on a new line (same indentation)
  excludedQualityProfiles:
    -
  defaultTags: # If set must be existing tags
    - telegram
  adminRestrictions: false

#Radarr Configuration
radarr:
  server:
    addr: 10.0.0.75
    port: 7878 # Default is 7878
    path: /movies/radarr/ # Default is / . If set, it must start and finish with / . Eg: /radarr/
    ssl: false #default false
  auth:
    apikey: xxxxxxxxxxx
    username: #
    password: #
  search: true
  minimumAvailability: announced
  excludedRootFolders: # If set must not have a trailing slash Eg: /mnt/Media
    - # First excluded folder, add others with a "-" on a new line (same indentation)
  excludedQualityProfiles:
    - #
  defaultTags: # If set must be existing tags
    - telegram
  adminRestrictions: false

#Telegram Configuration
telegram:
  token: xxxxxxxxxxx
  password: xxxxxxxxxxx

#Transmission Configuration
transmission:
  enable: true #enable the transmission commands
  onlyAdmin: true #transmission command will only work for admins
  host: 10.0.0.75 # IP-adres of the Transmission service
  authentication: true #is transmission protected with a password?
  username: xxxxxxxxxxx
  password: xxxxxxxxxxx

sabnzbd:
  enable: true
  onlyAdmin: true
  server:
    addr: #
    port: 8090 # Default is 8090
    path: / # Default is / . If set, it must start and finish with / . Eg: /sonarr/
    ssl: false #default false
  auth:
    apikey: #
    username: #
    password: #

Optional settings:
##Language
language: en-us # en-us, es-es, it-it, nl-be, pt-pt

##Entrypoints
entrypointAuth: auth #auth or a custom entrypoint
entrypointHelp: help #help entrypoint
entrypointAdd: start #start or a custom entrypoint
entrypointAllSeries: allSeries #allSeries or a custom entrypoint
entrypointAllMovies: allMovies #allMovies or a custom entrypoint
entrypointTransmission: transmission #transmission or a custom entrypoint
entrypointSabnzbd: sabnzbd #sabnzbd or a custom entrypoint

##Restrict some commands to only admins and/or provide extra authorization by usernames
enableAdmin: true #Check admin.txt
enableAllowlist: false #Check allowlist.txt - very restrictive!

##Logging
logToConsole: true
debugLogging: true
```
