### ISSUE TITLE
Can't Start Addarr

### ISSUE THREAD

**Issue by sNNNeaker** [Waterboy1602/Addarr#12]
Hi,
just installed Addarr, changed values in the config and tried to start it with `python addarr.py`.
I get the following error:

```
  File "addarr.py", line 42
    READ_CHOICE: [MessageHandler(Filters.regex(f'^({transcript["Movie"]}|{transcript["Serie"]})$'), search)],
                                                                                                ^
SyntaxError: invalid syntax
```

**Comment by Waterboy1602** [comment]
Are you sure you're using python3.6 or higher?

**Comment by sNNNeaker** [comment]
Thanks for the tip. Could it start with python3.6 (also had to install the reqs through 3.6).

Now I get the following. Please Help :) .

```
yaml.scanner.ScannerError: while scanning an alias
  in "/opt/addarr/config.yaml", line 10, column 19
expected alphabetic or numeric character, but found '.'
  in "/opt/addarr/config.yaml", line 10, column 27
```

My config.yaml:

```
#Sonarr Configuration
sonarr:
    server:
        addr: 123.456.789.012
        port: 8989
        ssl: false
    auth:
        apikey: 1234.....
        username: user
        password: *pw
    search: true
    rootFolder: /mnt/shows/
    seasonFolder: true
    qualityProfileId: 6



#Radarr Configuration
radarr:
    server:
        addr: 123.456.789.012
        port: 7878
        ssl:  false
    auth:
        apikey: 1234....
        username: user
        password: pw
    search: true
    rootFolder: /mnt/movies/
    qualityProfileId: 6

#Telegram Configuration
telegram:
    token: 1143000000:AAaaaaaaaaaaaaaaaaaaaaaaaaajf408rI_7EHZ4
    password:

#Language
language: en #'en' or 'nl'
```
