### ISSUE TITLE
Docker container on Synology keeps crashing

### ISSUE THREAD

**Issue by TheGianni** [Waterboy1602/Addarr#121]
Installed the docker container on a Synology NAS running DSM 7 following your guide in the wiki. Container doesn't start properly, keeps crashing. Unable to even start it up...

The container's network is set to "host". I'm not using transmission or sabnzbd.

Am I missing something? Appreciate your feedback/support!

Here's the addarr config:

```
#Sonarr Configuration
sonarr:
  server:
    addr: 192.168.0.5
    port : 8989 # Default is 8989
    path: /media/series # Default is / . If set, it must start and finish with / . Eg: /sonarr/
    ssl: false #default false
  auth:
    apikey: xxxxxxxxxxxxxxxxxxxxxxxxx
    username: xxxxxxxxx
    password: xxxxxxxxx
  search: true
  seasonFolder: true
  languageProfile: English
  excludedRootFolders: # If set must not have a trailing slash Eg: /mnt/Media
    - # First excluded folder, add others with a "-" on a new line (same indentation)
  excludedQualityProfiles:
    - 
  defaultTags: # If set must be existing tags
    - telegram
  adminRestrictions: true

#Radarr Configuration
radarr:
  server:
    addr: 192.168.0.5
    port : 8310 # Default is 7878
    path: /media/movies # Default is / . If set, it must start and finish with / . Eg: /radarr/
    ssl: false #default false
  auth:
    apikey: xxxxxxxxxxxxxxxxxxxxxxxxx
    username: xxxxxxxxxxxxxx
    password: xxxxxxxxxxxxx
  search: true
  minimumAvailability: announced
  excludedRootFolders: # If set must not have a trailing slash Eg: /mnt/Media
    - # First excluded folder, add others with a "-" on a new line (same indentation)
  excludedQualityProfiles:
    - 
  defaultTags: # If set must be existing tags
    - telegram
  adminRestrictions: true
  
#Telegram Configuration
telegram:
  token: xxxxxxxxxxxxxxxxxxxxxxxxxxx
  password: xxxxxxxxxxxxxxxxx

#Transmission Configuration
transmission:
  enable: false #enable the transmission commands
  onlyAdmin: true #transmission command  will only work for admins
  host: # IP-adres of the Transmission service
  authentication: true #is transmission protected with a password?
  username: 
  password:

sabnzbd:
  enable: false
  onlyAdmin: true
  server:
    addr:
    port: 8090 # Default is 8090
    path: / # Default is / . If set, it must start and finish with / . Eg: /sonarr/
    ssl: false #default false
  auth:
    apikey:
    username:
    password:

# Optional settings:
##Language
language: en-us # en-us, es-es, it-it, nl-be, pt-pt

##Entrypoints
entrypointAuth: auth #auth or a custom entrypoint
entrypointHelp: help #help entrypoint
entrypointAdd: start #start or a custom entrypoint
entrypointAllSeries: allSeries #allSeries or a custom entrypoint
entrypointAllMovies: allMovies #allMovies or a custom entrypoint
entrypointTransmission: transmission #transmission or a custom entrypoint
entrypointSabnzbd: sabnzbd #sabnzbd or a custom entrypoint

##Restrict some commands to only admins and/or provide extra authorization by usernames
enableAdmin: true #Check admin.txt
enableAllowlist: false #Check allowlist.txt - very restrictive!

##Logging
logToConsole: true
debugLogging: false

```
