### ISSUE TITLE
Bot Won't Accept Responses Unless There's a Preceding Slash /

### ISSUE THREAD

**Issue by spiveym** [Waterboy1602/Addarr#133]
I think this is potentially the same issue that was [noted here](https://github.com/Waterboy1602/Addarr/issues/70).

![This is the corresponding dialogue in Telegram.](https://user-images.githubusercontent.com/15334317/188342250-ab822878-7677-444a-a678-070a474d26cb.png)

```
2022-09-05T01:15:15.865317470Z 2022-09-05 01:15:15,864 - addarr - DEBUG - reply is /Godfather
2022-09-05T01:15:18.473844130Z 2022-09-05 01:15:18,471 - addarr.radarr - INFO - http://192.168.1.3:7878/api/v3/movie/lookup?apikey=xxx&term=/Godfather
2022-09-05T01:15:15.866343755Z 2022-09-05 01:15:15,865 - addarr - DEBUG - User entered a title /Godfather
```

The bot doesn't respond to me entering any text unless I put a forward slash in front of it, however, that plays up whenever there is a title with multiple words/spaces in the name. I do not have any adminRestrictions/enableAdmin config parameters enabled.

**Comment by Waterboy1602** [comment]
I tried to recreate the problem, but didn't experience the same issue. So I have no idea why it's not working with your instance.

![image](https://user-images.githubusercontent.com/24163882/190148390-3d54b940-fda0-4d87-8dc0-bc6f46cfeb6b.png)

This is the config I used:
```

# Optional settings:
##Language
language: en-us # en-us, es-es, it-it, nl-be, pt-pt, fr-fr, ru-ru

##Entrypoints
entrypointAuth: auth #auth or a custom entrypoint
entrypointHelp: help #help entrypoint
entrypointAdd: start #start or a custom entrypoint
entrypointDelete: delete #delete or a custom entrypoint
entrypointAllSeries: allSeries #allSeries or a custom entrypoint
entrypointAllMovies: allMovies #allMovies or a custom entrypoint
entrypointTransmission: transmission #transmission or a custom entrypoint
entrypointSabnzbd: sabnzbd #sabnzbd or a custom entrypoint

##Restrict some commands (Transmission) to only admins 
enableAdmin: false #Check admin.txt
enableAllowlist: false #Check allowlist.txt - very restrictive!

##Logging
logToConsole: true
debugLogging: true
```

**Comment by spiveym** [comment]
> I tried to recreate the problem, but didn't experience the same issue. So I have no idea why it's not working with your instance.

Here's my **docker-compose.yml** entry:

```
addarr:
    container_name: addarr
    image: waterboy1602/addarr:latest
    restart: "no"
    network_mode: host
    volumes:
    - ./volumes/addarr/config.yaml:/app/config.yaml:ro
    - ./volumes/addarr/chatid.txt:/app/chatid.txt:rw
    - ./volumes/addarr/admin.txt:/app/admin.txt:ro
    - ./volumes/addarr/logs:/app/logs:rw
```

```
#Sonarr Configuration
sonarr:
  server:
    addr: 192.168.1.3
    port : 8989 # Default is 8989
    path: / # Default is / . If set, it must start and finish with / . Eg: /sonarr/
    ssl: false #default false
  auth:
    apikey: [redacted]
    username: #
    password: #
  search: true
  seasonFolder: true
  languageProfile: English
  excludedRootFolders: # If set must not have a trailing slash Eg: /mnt/Media
    - # First excluded folder, add others with a "-" on a new line (same indentation)
  excludedQualityProfiles:
    - #
  defaultTags: # If set must be existing tags
    - telegram
  adminRestrictions: false

#Radarr Configuration
radarr:
  server:
    addr: 192.168.1.3
    port : 7878 # Default is 7878
    path: / # Default is / . If set, it must start and finish with / . Eg: /radarr/
    ssl: false #default false
  auth:
    apikey: [redacted]
    username: #
    password: #
  search: true
  minimumAvailability: announced
  excludedRootFolders: # If set must not have a trailing slash Eg: /mnt/Media
    - # First excluded folder, add others with a "-" on a new line (same indentation)
  excludedQualityProfiles:
    - #
  defaultTags: # If set must be existing tags
    - telegram
  adminRestrictions: false

#Telegram Configuration
telegram:
  token: [redacted]
  password: [redacted]

#Transmission Configuration
transmission:
  enable: false #enable the transmission commands
  onlyAdmin: false #transmission command  will only work for admins
  host: # IP-adres of the Transmission service
  authentication: true #is transmission protected with a password?
  username:
  password:

sabnzbd:
  enable: false
  onlyAdmin: false
  server:
    addr:
    port: 8090 # Default is 8090
    path: / # Default is / . If set, it must start and finish with / . Eg: /sonarr/
    ssl: false #default false
  auth:
    apikey:
    username:
    password:

# Optional settings:
##Language
language: en-us # en-us, es-es, it-it, nl-be, pt-pt, fr-fr, ru-ru

##Entrypoints
entrypointAuth: auth #auth or a custom entrypoint
entrypointHelp: help #help entrypoint
entrypointAdd: start #start or a custom entrypoint
entrypointAllSeries: allSeries #allSeries or a custom entrypoint
entrypointAllMovies: allMovies #allMovies or a custom entrypoint
entrypointTransmission: transmission #transmission or a custom entrypoint
entrypointSabnzbd: sabnzbd #sabnzbd or a custom entrypoint

##Restrict some commands to only admins and/or provide extra authorization by usernames
enableAdmin: false #Check admin.txt
enableAllowlist: false #Check allowlist.txt - very restrictive!

##Logging
logToConsole: true
debugLogging: true
```
