### ISSUE TITLE
Finds, but does not add series "Unfortunately, it was not possible to add the series. To start a new search, enter - films"

### ISSUE THREAD

**Issue by bulletproof2k** [Waterboy1602/Addarr#159]
```
sonarr:
  server: 
    addr: localhost
    port : 8989 # Default is 8989
    path: / # Default is / . If set, it must start and finish with / . Eg: /sonarr/
    ssl: false # Default false
  auth:
    apikey: mySecretApiKey12345
    username: 
    password:
  search: true # Start search after adding series
  seasonFolder: true
  languageProfile: Russian
  excludedRootFolders: # If set must not have a trailing slash Eg: /mnt/Media
    - # First excluded folder, add others with a "-" on a new line (same indentation)
  narrowRootFolderNames: true # If true, only the last folder name will be shown instead of full path
  excludedQualityProfiles:
    - 
  defaultTags: # If set must be existing tags
    - telegram
  addRequesterIdTag: true # Add telegram user id as tag on series
  adminRestrictions: false
```
Maybe I set something wrong in the settings with the movie everything is OK.
[addarr.log](https://github.com/Waterboy1602/Addarr/files/14875000/addarr.log)
