### ISSUE TITLE
Docker can't start develop branch

### ISSUE THREAD

**Issue by Sivarius** [Waterboy1602/Addarr#174]
Here are 2 log files
1st one is from pull addar:develop
2nd one - trying build from source and compose file 

Also 
Compose config

```
version: '3'
services:
  addarr:
    container_name: dedarr
    image: waterboy1602/addarr:develop
    restart: unless-stopped
    networks:
      - mediaserver
    volumes:
    - /volume1/docker/deddar/config/config.yaml:/app/config.yaml:rw
    - /volume1/docker/deddar/config/chatid.txt:/app/chatid.txt:rw
    - /volume1/docker/deddar/config//admin.txt:/app/admin.txt:rw
    - /volume1/docker/deddar/config/allowlist.txt:/app/allowlist.txt:rw
    - /volume1/docker/deddar/logs:/app/logs:rw
    
    environment:
      - PUID=1024
      - PGID=100

networks:
  mediaserver:
    external: true
```

[addarlogs.zip](https://github.com/user-attachments/files/20589998/addarlogs.zip)
