### ISSUE TITLE
mapping values are not allowed here

### ISSUE THREAD

**Issue by rubino1896** [Waterboy1602/Addarr#39]
Sorry i am new to all this, but i am verry interested in addarr for radarr with telegram. Looks awesome!
I get this error. Is someone knowing what this means? 

![addarr](https://user-images.githubusercontent.com/76480008/102889079-46c51a80-445a-11eb-8d59-647001be6b6b.png)

**Comment by Waterboy1602** [comment]
Could you send me your `config.yaml` file? I assume their will be some wrong configurations there.

**Comment by rubino1896** [comment]
Thank you very much for helping. See the config file attached.

Op di 22 dec. 2020 om 13:58 schreef Wannes <notifications@github.com>:

**Comment by Waterboy1602** [comment]
I didn't get the file you've send, but you could put it here. Just don't forget to remove your API-keys from the `config.yaml` file.

**Comment by rubino1896** [comment]
I can not send it by mail, of as attatchment in this comment. 

#Restrict some commands (Transmission) to only admins 
enableAdmin: true

#Sonarr Configuration
sonarr:
  server:
    addr: 
    port : 8989 # Default is 8989
    path: / # Default is / . If set, it must start and finish with / . Eg: /sonarr/
    ssl: false #default false
  auth:
    apikey: 
    username: 
    password:
  search: true
  seasonFolder: true
  qualityProfileId: 1

#Radarr Configuration
radarr:
  server:192.168.1....
    addr:
    port : 7878 # Default is 7878
    path: / # Default is / . If set, it must start and finish with / . Eg: /radarr/
    ssl: false #default false
  auth:
    apikey:15e6......
    username:
    password: 
  search: true
  qualityProfileId: 1

#Telegram Configuration
telegram:
  token:149803........
  password:

#Transmission Configuration
transmission:
  enable: true #enable the transmission commands
  onlyAdmin: true #transmission command  will only work for admins
  host:
  authentication: true #is transmission protected with a password?
  username: 
  password:

#Language
language: en

#Entrypoints
entrypointAuth: auth #auth or a custom entrypoint
entrypointAdd: start #start or a custom entrypoint
entrypointAllSeries: allSeries #allSeries or a custom entrypoint
entrypointTransmission: transmission #transmission or a custom entrypoint

#Logging
logToConsole: true
debugLogging: false

**Comment by Waterboy1602** [comment]
I see here and there that you don't have a space after `:`. To make the `config.yaml` work there must be a space between `:` and your setting.

Also make sure your intendations are correct. This can also sometimes break the Addarr.

**Comment by rubino1896** [comment]
I put a space between the setting, but the error still appears. I only have 3 settings to put in. Those are all sort of in the command above. Is there a setting that is blank, but is very important? i dont have an username of pasword for radarr or telegram.

**Comment by Waterboy1602** [comment]
`Mapping values are not allowed here` does mean that there isn't a space after the `:`. As you can see in your log it's referencing to line 22. Thats this setting: `addr: 192.168.1....`. So be sure you've put the spaces correctly. 

This is how your `config.yaml` should look like:
```
#Restrict some commands (Transmission) to only admins 
enableAdmin: true

#Sonarr Configuration
sonarr:
  server:
    addr: 
    port : 8989 # Default is 8989
    path: / # Default is / . If set, it must start and finish with / . Eg: /sonarr/
    ssl: false #default false
  auth:
    apikey: 
    username: 
    password:
  search: true
  seasonFolder: true
  qualityProfileId: 1

#Radarr Configuration
radarr:
  server:
    addr: 192.168.1....
    port : 7878 # Default is 7878
    path: / # Default is / . If set, it must start and finish with / . Eg: /radarr/
    ssl: false #default false
  auth:
    apikey: 15e6......
    username:
    password: 
  search: true
  qualityProfileId: 1

#Telegram Configuration
telegram:
  token: 149803........
  password:

#Transmission Configuration
transmission:
  enable: true #enable the transmission commands
  onlyAdmin: true #transmission command  will only work for admins
  host:
  authentication: true #is transmission protected with a password?
  username: 
  password:

#Language
language: en

#Entrypoints
entrypointAuth: auth #auth or a custom entrypoint
entrypointAdd: start #start or a custom entrypoint
entrypointAllSeries: allSeries #allSeries or a custom entrypoint
entrypointTransmission: transmission #transmission or a custom entrypoint

#Logging
logToConsole: true
debugLogging: false
```

**Comment by rubino1896** [comment]
I am sure all the settings have a space between. See below: 

#Restrict some commands (Transmission) to only admins 
enableAdmin: true

#Sonarr Configuration
sonarr:
  server:
    addr: 
    port : 8989 # Default is 8989
    path: / # Default is / . If set, it must start and finish with / . Eg: /sonarr/
    ssl: false #default false
  auth:
    apikey: 
    username: 
    password:
  search: true
  seasonFolder: true
  qualityProfileId: 1

#Radarr Configuration
radarr:
  server: 192.168.1......
    addr:
    port : 7878 # Default is 7878
    path: / # Default is / . If set, it must start and finish with / . Eg: /radarr/
    ssl: false #default false
  auth:
    apikey: 15e6d4e........
    username:
    password: 
  search: true
  qualityProfileId: 1

#Telegram Configuration
telegram:
  token: 149803.......
  password:

#Transmission Configuration
transmission:
  enable: true #enable the transmission commands
  onlyAdmin: true #transmission command  will only work for admins
  host:
  authentication: true #is transmission protected with a password?
  username: 
  password:

#Language
language: en

#Entrypoints
entrypointAuth: auth #auth or a custom entrypoint
entrypointAdd: start #start or a custom entrypoint
entrypointAllSeries: allSeries #allSeries or a custom entrypoint
entrypointTransmission: transmission #transmission or a custom entrypoint

#Logging
logToConsole: true
debugLogging: false

**Comment by Waterboy1602** [comment]
If that is a copy, it looks like your intendation are wrong. Make sure you keep them like they are in `config-example.yaml` or as you can see in the example I've given.

**Comment by rubino1896** [comment]
I did, its probably because its copied into the comment. It keeps failing on line 21. That is the addr from radarr. What do i need to fill in there? i have tried the ip with port, also without the port. 

Stil thank you for helping. I know i am a nood at this...

**Comment by Waterboy1602** [comment]
You should just fill in the IP-adres without port. The port has to be filled in on the next line.

**Comment by rubino1896** [comment]
Sorry for the late reply. Its still not working unfortunatly, but now its line 21. That is the address. i have no idea what to fill in there. Any suggetions? 

Still thanks alot for helping!

**Comment by Waterboy1602** [comment]
This is how the Radarr part should be filled in:
```
#Radarr Configuration
radarr:
  server:
    addr: 192.168.1.X
    port: 7878 # Default is 7878
    ssl: false #default false
  auth:
    apikey: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    username: 
    password:
  search: true
  rootFolder: 
  qualityProfileId: 1
```
