### ISSUE TITLE
Instruction

### ISSUE THREAD

**Issue by Erthanos** [Waterboy1602/Addarr#57]
Hey, 

i can't figure out how to set this up whit the instruction given to me😅. can you guys make a youtube video or a configuration instruction for windows pls :)

**Comment by Waterboy1602** [comment]
Have you already tried following the [Windows wiki](https://github.com/Waterboy1602/Addarr/wiki/Installation-on-Windows)? If so, where exactly do you experience any problems?

**Comment by Erthanos** [comment]
Yes i have but,
I have 2 problems one is the i really dont now if my config file is good can i give a random bot token that i maked via botfather or do i need to use some other bot and how can i check if everything and is configured good?
(See config)

and the second problem is when i do the last step (python addarr.py) i get the next error ( C:/path where python is installed...../python.exe: error while loading shared libraries: ? : cannot open shared object file: No such file or directory ) don't really know but i think its need to search in the raddarr folder right?

(Config)
## everything that's empty i don't really know what to fill in
## sorry bothering you. i  wanted to learn it. only i don't understand it and is hard to find some info over this. 
##    I and my friend tried to get it working, but after hours spend i thought asking for help is maybe the best thing now hihi :)
####
#Sonarr Configuration
sonarr:
  server:
    addr: http://localhost:38082 <----can i use this so?
    port : 38082 # Default is 8989
    path: C:\ProgramData\NzbDrone
    ssl: false #default false
  auth:
    apikey:************* i know how to get
    username: 
    password:
  search: true
  seasonFolder: true
  qualityProfileId: 1
  excludedRootFolders: E:\Serie
    - 
###I don't use now maybe later 
#Radarr Configuration
radarr:
  server:
    addr:
    port : 7878 # Default is 7878
    path: / # Default is / . If set, it must start and finish with / . Eg: /radarr/
    ssl: false #default false
  auth:
    apikey:
    username:
    password: 
  search: true
  qualityProfileId: 1
  excludedRootFolders: # If set, must start and finish with / Eg: /mnt/Media/
    -
###if i put here a password do i created one for the bot or if my bot has no password can i let this empty
#Telegram Configuration
telegram:
  token:************ standaard Bot that i created via botfather, bot token 
  password:

###don't know what to do here 
#Transmission Configuration
transmission:
  enable: true #enable the transmission commands
  onlyAdmin: true #transmission command  will only work for admins
  host: # IP-adres of the Transmission service
  authentication: true #is transmission protected with a password?
  username: 
  password:

###i think this is ok
# Optional settings:
##Language
language: en

##Entrypoints
entrypointAuth: auth #auth or a custom entrypoint
entrypointHelp: help #help entrypoint
entrypointAdd: start #start or a custom entrypoint
entrypointAllSeries: allSeries #allSeries or a custom entrypoint
entrypointTransmission: transmission #transmission or a custom entrypoint

##Restrict some commands (Transmission) to only admins 
enableAdmin: true

##Logging
logToConsole: true
debugLogging: false

**Comment by Erthanos** [comment]
Yes i have but,
I have 2 problems one is the i really dont now if my config file is good can i give a random bot token that i maked via bot father or do i need to use some other bot and how can i check if everything and is configured good?
(See config)

and the second problem is when i do the last step (python addarr.py) i get the next error ( C:/path where python is installed...../python.exe: error while loading shared libraries: ? : cannot open shared object file: No such file or directory ) don't really know but i think its need to search in the raddarr folder right?
(Config)

[config.txt](https://github.com/Waterboy1602/Addarr/files/6125228/config.txt)

**Comment by Waterboy1602** [comment]
I've looked into your `config.yaml` and made some changes to how it should be.

For the Python problem: can you try executing `python --version` and send me the result you get? To me it looks like Python isn't installed correctly.

```
#Sonarr Configuration
sonarr:
  server:
    addr: http://localhost # No need to add the port here
    port : 38082 # Default is 8989
    path: # This is supposed to be an url path, not a file location
    ssl: false #default false
  auth:
    apikey: ************* i know how to get
    username: 
    password:
  search: true
  seasonFolder: true
  qualityProfileId: 1
  excludedRootFolders: E:\Serie
  
###I don't use now maybe later 
#Radarr Configuration
radarr:
  server:
    addr:
    port : 7878 # Default is 7878
    path: / # Default is / . If set, it must start and finish with / . Eg: /radarr/
    ssl: false #default false
  auth:
    apikey:
    username:
    password: 
  search: true
  qualityProfileId: 1
  excludedRootFolders: # If set, must start and finish with / Eg: /mnt/Media/

###if i put here a password do i created one for the bot or if my bot has no password can i let this empty
# --> the password you fill in here is to authorize a chat to use Addarr. You have to fill a password in (you can choose one yourself).
#Telegram Configuration
telegram:
  token:************ standaard Bot that i created via botfather, bot token 
  password:

###don't know what to do here 
# --> You only need to fill this in of you use Transmission. If you don't use it, you can fill in "enable: false"
#Transmission Configuration
transmission:
  enable: true #enable the transmission commands
  onlyAdmin: true #transmission command  will only work for admins
  host: # IP-adres of the Transmission service
  authentication: true #is transmission protected with a password?
  username: 
  password:

###i think this is ok
# Optional settings:
##Language
language: en

##Entrypoints
entrypointAuth: auth #auth or a custom entrypoint
entrypointHelp: help #help entrypoint
entrypointAdd: start #start or a custom entrypoint
entrypointAllSeries: allSeries #allSeries or a custom entrypoint
entrypointTransmission: transmission #transmission or a custom entrypoint

##Restrict some commands (Transmission) to only admins 
enableAdmin: true

##Logging
logToConsole: true
debugLogging: false
```
