### ISSUE TITLE
No ip or port defined.  Generate of APIQUERY failed: unsupported operand type(s) for +: 'NoneType' and 'str'.

### ISSUE THREAD

**Issue by keteague** [Waterboy1602/Addarr#65]
2021-04-25 15:50:48,600 - addarr - DEBUG - Addarr v0.3 starting up...
2021-04-25 15:50:48,614 - addarr - INFO - Start chatting with Addarr in Telegram. The first time you use "start" you will be asked to enter your password.
2021-04-25 15:51:13,791 - addarr - DEBUG - User entered a title /Godfather
2021-04-25 15:51:17,485 - addarr.commons - WARNING - No ip or port defined.
2021-04-25 15:51:17,485 - addarr.commons - WARNING - Generate of APIQUERY failed: unsupported operand type(s) for +: 'NoneType' and 'str'.

I receive the above error in my log file when I attempt to add.  The process I use is:
/start
Enter the title:
/Godfather
Is this a movie or a series?
Movie
It's when I click on "Movie" when I receive the above error and the bot does not continue to the next step.  I can type /end and the bot will end the input session.

I'm not really sure how to tell which version I'm on or which version I was using previously.  I just ran a git clone today.  Previously, I was running whichever build was available on February 17, 2020.  

I copied over my previous chatid.txt and config.yaml file from the old version and modified it to include the necessary parameters for the current version.  Anything listed in **bold face text** below is either new or changed from my old config.yaml file.

```
#Restrict some commands (Transmission) to only admins
enableAdmin: true

#Sonarr Configuration
sonarr:
  server:
    addr: myweb.host.com
    port : 8989 # Default is 8989
    ssl: false #default false
  auth:
    apikey: myAPIkey
    username: myUserID
    password: myPassword
  search: true
  seasonFolder: true
  qualityProfileId: 1

#Radarr Configuration
radarr:
  server:
    addr: myweb.host.com
    port : 7878 # Default is 7878
    ssl: false #default false
  auth:
    apikey: myAPIkey
    username: myUserID
    password: myPassword
  search: true
  qualityProfileId: 1

#Telegram Configuration
telegram:
  token: myToken
  password: myPassword

#Transmission Configuration
transmission:
  enable: false #enable the transmission commands
  onlyAdmin: true #transmission command  will only work for admins
  host:
  authentication: true #is transmission protected with a password?
  username:
  password:

sabnzbd:
  enable: false
  onlyAdmin: true
  server:
    addr:
    port: 8090 # Default is 8090
    path: / # Default is / . If set, it must start and finish with / . Eg: /sonarr/
    ssl: false #default false
  auth:
    apikey:
    username:
    password:

#Language
language: en

#Entrypoints
entrypointAuth: auth #auth or a custom entrypoint
entrypointHelp: help #help entrypoint
entrypointAdd: start #start or a custom entrypoint
entrypointAllSeries: allSeries #allSeries or a custom entrypoint
entrypointAllMovies: allMovies #allMovies or a custom entrypoint
entrypointTransmission: transmission #transmission or a custom entrypoint
entrypointSabnzbd: sabnzbd #sabnzbd or a custom entrypoint

#Logging
logToConsole: false
debugLogging: true

```

**Comment by Waterboy1602** [comment]
If you're running the latest version of Addarr, then it looks like you're missing a setting option in your `config.yaml` file. One of the latest PR added an option to define a path to Sonarr and Radarr. Like under `server`, there you see the option `path`:

```
#Sonarr Configuration
sonarr:
  server:
    addr: 
    port : 8989 # Default is 8989
    path: / # Default is / . If set, it must start and finish with / . Eg: /sonarr/
    ssl: false #default false
  auth:
    apikey: 
    username: 
    password:
  search: true
  seasonFolder: true
  qualityProfileId: 1
  excludedRootFolders: # If set must start and finish with / Eg: /mnt/Media/
    - 

#Radarr Configuration
radarr:
  server:
    addr:
    port : 7878 # Default is 7878
    path: / # Default is / . If set, it must start and finish with / . Eg: /radarr/
    ssl: false #default false
  auth:
    apikey:
    username:
    password: 
  search: true
  qualityProfileId: 1
  excludedRootFolders: # If set, must start and finish with / Eg: /mnt/Media/
```
