### ISSUE TITLE
Oops, failed to add the movie/series. Maybe give it another try.

### ISSUE THREAD

**Issue by ghost** [Waterboy1602/Addarr#96]
Hi,

We're getting the error that Addarr fails to add a movie or series. Looking up series and listing all movies/series goes fine, but as soon as we choose "Yes, add this", we get the error.

config.yaml
```
sonarr:
  server:
    addr: localhost
    port : 8989
    path: /
    ssl: false
  auth:
    apikey: xxx
    username: #
    password: #
  search: true
  seasonFolder: true
  qualityProfileId: 1
  languageProfileId: 1
  excludedRootFolders:
    - #

radarr:
  server:
    addr: localhost
    port : 7878
    path: /
    ssl: false
  auth:
    apikey: xxx
    username: #
    password: #
  search: true
  qualityProfileId: 1
  minimumAvailability: released
  excludedRootFolders:
    - #

telegram:
  token: xxx
  password: xxx

transmission:
  enable: false
  onlyAdmin: true
  host: localhost
  authentication: true
  username: #
  password: #

sabnzbd:
  enable: false
  onlyAdmin: true
  server:
    addr: localhost
    port: 8090
    path: /
    ssl: false
  auth:
    apikey: #
    username: #
    password: #

language: en-us

entrypointAuth: auth
entrypointHelp: help
entrypointAdd: start
entrypointAllSeries: allSeries
entrypointAllMovies: allMovies
entrypointTransmission: transmission
entrypointSabnzbd: sabnzbd

enableAdmin: true

logToConsole: true
debugLogging: true
```

Logs
```
2022-01-03 20:47:49,132 - addarr.radarr - DEBUG - Found Radarr paths: [{'path': '/movies', 'accessible': True, 'freeSpace': xxx, 'unmappedFolders': [{list of movie folders}]
2022-01-03 20:47:49,133 - addarr - DEBUG - Excluded root folders: [None]
2022-01-03 20:47:49,133 - addarr - DEBUG - Only found 1 path, so proceeding with that one...
2022-01-03 20:47:50,996 - addarr - DEBUG - Removing choice, title, position, paths, and output from context.user_data...
```

Any idea where it goes wrong? We're using Traefik reverse proxy, but the ports for Sonarr/Radarr are exposed and accessible for the Addarr container.

Thank you.
